<?php

/**
 * @file
 * A block module that displays votes between given times.
 */

/**
 * Implements hook_block_info().
 */
function dummy_calendar_block_info() {
  $blocks['dummy_calendar'] = array(
    'info' => t('Calendar Date Picker'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 * 
 * Prepares the contents of the block.
 */
function dummy_calendar_block_view($delta = '') {
	switch($delta){
		case 'dummy_calendar':
			$block['subject'] = t('Coffee Agenda: ');
			$block['content'] = "";
			if(user_access('access content')){
			
				$today = agenda_manager_date_of_interest();
			  
				$block['subject'] .= "Date Picker";
				
				$block['content'] .= "<div id='dummy-calendar-block'>";
				$block['content'] .= dummy_calendar_content($today);
				$block['content'] .= "</div>";
			}
			return $block;
	}

}

function dummy_calendar_datelink_path($time) {
 	$date_pattern = '/\d{4}\-\d{2}\-\d{2}/i';
    
    // replace date with date of interest in current path
    if( preg_match($date_pattern, current_path()) ) {
        $path = preg_replace($date_pattern, date("Y-m-d", $time), current_path());
    } else {
        $path = current_path()."/".date("Y-m-d", $time);
    }

    return base_path().$path;
}

function dummy_calendar_datelink($time) {

	$path = dummy_calendar_datelink_path($time);
	
	return "<a href='".$path."'>".date("j", $time)."</a>";
}

function dummy_calendar_dayname($i) {
	switch($i) {
		case 0:
			return 'sunday';
			break;
		case 1:
			return 'monday';
			break;
		case 2:
			return 'tuesday';
			break;
		case 3:
			return 'wednesday';
			break;
		case 4:
			return 'thursday';
			break;
		case 5:
			return 'friday';
			break;
		case 6:
			return 'saturday';
			break;
	}
}

function dummy_calendar_content($time) {

	$today = $time;
	$content = "";
	
	$content .= "<div id='dummy-calendar-block-header'>
					<a class='dummy_calendar_pager_prev' href='".dummy_calendar_datelink_path(strtotime("-1 month", $time))."'>Prev</a>
					".date("F", $today);
	$nextmonth = strtotime("first day of next month", $time);
	if($nextmonth > time()) {
		$content .= "<span class='dummy_calendar_pager_dead'>Next</span>";
	} else {
		$content .= "<a class='dummy_calendar_pager_next' href='".dummy_calendar_datelink_path($nextmonth)."'>Next</a>";
	}
	$content .= "</div>";
		
	$content .= "<div id='dummy-calendar-block-display'>";
		$ndays = date("t", $today);
		$firstday = date("N",strtotime("first day of this month", $today)) % 7;
		
		$content .= "<table cellspacing='0' cellpadding='0'><tr>";
		for($i = 0; $i <= 6; $i++) {
			$content .= "<th>".substr("SMTWTFS", $i, 1)."</th>";
		}
		$content .= "</tr><tr>";
		
		for($i = 0; $i < $firstday; $i++) {
			// last month
			$date = strtotime("last ".dummy_calendar_dayname($i)." of last month", $today);
			$content .= "<td class='other-month'>"
								.dummy_calendar_datelink( $date )
								."</td>";
		}

		for($i = 1; $i <= $ndays; $i++) {
			if(($i + $firstday) % 7 == 1) {
				$content .= "</tr><tr>";
			}
			$date = strtotime($i.date(" F Y", $today));
			$classes = "";
			if(($i+$firstday)%7 == 0 || ($i+$firstday)%7 == 1) {
				$classes .= ' weekend';
			} else {
				$classes .= ' weekday';
			}
			if(date("j", $today) == date("j", $date)) {
				$classes .= ' today';
			}
			
			if($date < time()) {
				$content .= "<td class='".$classes."'>".dummy_calendar_datelink($date)."</td>";
			} else {
				$content .= "<td class='".$classes."'><span class='nolink'>".$i."</span></td>";
			}
		}
		

		for( $i = 0; $i < 7 - ($ndays + $firstday) % 7 && ($ndays + $firstday) % 7; $i++) {
			// next month
			$date = strtotime("first ".dummy_calendar_dayname( ( $ndays + $firstday + $i ) % 7 )." of next month", $today);
			if($date < time()) {
				$content .= "<td class='other-month'>".dummy_calendar_datelink($date)."</td>";
			} else {
				$content .= "<td class='other-month'>".date("j", $date)."</td>";
			}
		}
		$content .= "</tr></table>";
		
	$content .= "</div>";
	
	return $content;
}
