<?php

function ratejax_get_votes() {
	global $user;
	$uid = 1*($user->uid);
	
	if($uid) {
	
		$current_date = agenda_manager_date_of_interest();
		$last_date = strtotime("-3 days", $current_date);
		$next_date = strtotime("+3 days", $current_date);

	
		$query = db_select('votingapi_vote', 'v')
					->fields('v', array('entity_id', 'value'))
					->condition('uid', $uid)
					->condition('tag', "vote")
					->condition('timestamp', array($last_date, $next_date), 'BETWEEN')
				->execute();
	} else {
		$query = array();
	}
	
	return $query;

}

function ratejax_init() {

	$result = ratejax_get_votes();
	$ratejax_votes = array();
	foreach ($result as $vote){
		$ratejax_votes["vote".($vote->entity_id)] = $vote->value;
	}

	drupal_add_js(array('ratejax' => $ratejax_votes), 'setting');
}
